substitutions:
  _FIREBASE_PROJECT: "tbsignalstream"

steps:
# Install deps and build using a Node image so the build runs remotely in Cloud Build
- name: 'node:18'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      set -e
      npm ci
      npm run build

# Install firebase-tools and deploy the built app to App Hosting `studio` using the substituted project id
- name: 'node:18'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      set -e
      npm install -g firebase-tools
      firebase deploy --only apphosting:studio --project=${_FIREBASE_PROJECT}

timeout: '1200s'
