"""
URGENT: Current Strategy is LOSING Money!
Baseline Results: 38.31% WR, -67.78% returns, 0.87 PF

IMMEDIATE ACTION: Test Aggressive Baseline
This uses MUCH stricter filters to achieve 65%+ WR
"""

print("="*80)
print("❌ CURRENT STRATEGY RESULTS (1 YEAR)")
print("="*80)
print("Win Rate:       38.31% (LOSING 62% of trades)")
print("Returns:        -67.78% (MASSIVE LOSS)")
print("Profit Factor:  0.87 (Losing money)")
print()
print("💡 DIAGNOSIS: Strategy is too loose - taking too many bad trades")
print("   → Need STRICTER filters to only take high-conviction setups")
print()

print("="*80)
print("🎯 AGGRESSIVE BASELINE - TEST THIS NEXT")
print("="*80)
print()
print("Copy these parameters to Dashboard Strategy Backtester:")
print()
print("📊 BASIC SETTINGS:")
print("   Strategy: Alpha-Ensemble")
print("   Date Range: Nov 1, 2025 - Dec 18, 2025")
print("   Capital: ₹100,000")
print()
print("🔬 SCREENING FILTERS (Much Stricter):")
print("   ✓ EMA Period: 200")
print("   ✓ ADX Threshold: 25 (vs current 20 - STRONGER trends only)")
print("   ✓ RSI Oversold: 35 (vs 30 - TIGHTER)")
print("   ✓ RSI Overbought: 65 (vs 70 - TIGHTER)")
print("   ✓ Volume Multiplier: 2.0x (vs 1.5x - HIGHER volume required)")
print()
print("💰 RISK MANAGEMENT (Better exits):")
print("   ✓ Risk:Reward: 3.0 (vs 2.5 - Let winners run longer)")
print("   ✓ Stop Loss: 2.0 ATR (vs 1.5 - Wider to avoid noise)")
print("   ✓ Position Size: 2% per trade")
print("   ✓ Max Positions: 3 (vs 5 - More focused)")
print()
print("⏰ TIMING (Avoid bad hours):")
print("   ✓ Trading Hours: 10:00 AM - 2:30 PM (avoid open/close chaos)")
print("   ✓ Timeframe Alignment: 5min + 15min + hourly (3 must align)")
print()
print("📈 UNIVERSE:")
print("   ✓ Symbols: Nifty 100 (100 most liquid stocks)")
print()
print("="*80)
print("🎯 EXPECTED IMPROVEMENTS:")
print("="*80)
print("Current:  38% WR, -68% returns, 0.87 PF")
print("Target:   55-65% WR, +50% returns, 3.0+ PF")
print()
print("Key Changes That Will Help:")
print("   1. ADX > 25 = Only strong trending moves (not weak/choppy)")
print("   2. Volume 2.0x = Real institutional participation")
print("   3. RSI 35/65 = Avoid extreme overbought/oversold")
print("   4. 3 timeframes aligned = Multi-timeframe confirmation")
print("   5. Wider stops = Less noise, better runners")
print("   6. Higher R:R = Bigger winners, same-size losers")
print()
print("="*80)
print("📋 ACTION ITEMS:")
print("="*80)
print("1. ✅ Note current results: 38.31% WR, -67.78% returns")
print("2. ⏳ Run Aggressive Baseline with params above")
print("3. ⏳ Compare results:")
print("   - If WR improves to 45-50%+: CONTINUE with 12 batches")
print("   - If WR still below 45%: Parameters too strict, adjust")
print()
print("4. ⏳ Goal: Find config that gives 65%+ WR")
print()
print("="*80)
print("💡 WHY CURRENT STRATEGY FAILS:")
print("="*80)
print("Too many low-quality trades:")
print("   ❌ ADX 20 = Catches weak trends AND choppy markets")
print("   ❌ RSI 30/70 = Too wide, catches failing bounces")
print("   ❌ Volume 1.5x = Not enough conviction")
print("   ❌ 2.5 R:R = Winners don't run far enough")
print("   ❌ 1.5 ATR stops = Too tight, gets stopped out in noise")
print()
print("Aggressive filters will:")
print("   ✅ Reject weak setups (fewer trades, higher quality)")
print("   ✅ Only trade strong trends (ADX > 25)")
print("   ✅ Wait for real volume (2.0x avg)")
print("   ✅ Multi-timeframe confirmation (3 TFs align)")
print("   ✅ Let winners run (3:1 R:R)")
print()
print("="*80)
print("🚀 START AGGRESSIVE BASELINE TEST NOW!")
print("="*80)
print()
print("Expected outcome:")
print("   • Fewer trades (maybe 15-25 instead of 50+)")
print("   • MUCH higher win rate (50-65% instead of 38%)")
print("   • Positive returns (vs -68%)")
print("   • Profit factor > 2.0 (vs 0.87)")
print()
print("If this works, continue with 12-batch optimization to fine-tune to 65%+!")
print()
